name: Test Suite

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  test:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            container: "" # Runs directly on the Ubuntu host
            install: sudo apt-get update && sudo apt-get install -y libncurses-dev
          
          - os: ubuntu-latest
            container: archlinux:latest # Runs inside an Arch Docker container
            install: pacman -Syu --noconfirm ncurses make gcc 
      fail-fast: false

    runs-on: ${{ matrix.os }}
    
    container: ${{ matrix.container != '' && matrix.container || 'null' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: ${{ matrix.install }}

      - name: Run tests
        run: make test